### ISSUE TITLE
Inappropriate method call

### ISSUE THREAD

**Issue by vudeam** [Betaron/vk_feed_parser#6]
The assignment of return value of `MainWindow.GetConfig()` is not needed, as the Config's properties are assigned in the `Parser.ReadConfig()` method.

https://github.com/Betaron/vk_feed_parser/blob/c9721d5dd3b4ac631e25428e92a8d9dec65ba7b8/vk_feed_parser/Windows/MainWindow.xaml.cs#L32

**Comment by Betaron** [comment]
Oh, you actually right. I'll do that in the nearest future.
